name: Confluence to Markdown

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Python install requirements
        run: |
          python -m pip install -r src/requirements.txt
      - name: Run unit tests
        run: |
          python -m unittest discover -s tests -p "test_*.py" -v
